config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
selly_dbt:
  outputs:
    prod:
      dbname: mongo_etl
      host: localhost
      pass: bvxJaDGW2R55uyDXfODJ2a0Y
      port: 5432
      schema: public
      threads: 32
      type: postgres
      user: selly
  target: prod
